{
 "title": "NodeJS App",
 "tags": [
  "nodejs",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Process CPU %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[1m]) * 100",
     "legendFormat": "cpu user"
    }
   ]
  },
  {
   "title": "Heap Used MB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds" }
   ]
  },
  {
   "title": "HTTP Requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m]))"
    }
   ]
  }
 ]
}